### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by freopt** [Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.12.2#41] opened 2022-05-11 16:09 UTC
**Describe the bug**
The game just crahsed while walking around

**To Reproduce**
I don't really know

**please complete the following information:**
 - Forge Version: 14.23.52860
 - Mods: in crash report
 - MO Version 0.7.9

[crash-2022-05-11_12.01.29-server.txt](https://github.com/Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.12.2/files/8671636/crash-2022-05-11_12.01.29-server.txt)

**Comment by infiniteblock** [comment] 2022-05-12 04:38
looks like #9 again i just cant seem to reproduce, do you have a link to the modpack? also maybe a copy of the world?

**Comment by infiniteblock** [comment] 2022-05-12 05:01
[MatterOverdrive-1.12.2-0.8.0-universal.zip](https://github.com/Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.12.2/files/8675119/MatterOverdrive-1.12.2-0.8.0-universal.zip)

Could you try this if u still have the crashing world? you will need to extract the jar from the zip

**Comment by freopt** [comment] 2022-05-13 00:35
I deleted the world but so far I haven't crashed with new version including when I go up to the structure that I think crashed me (it happened again after I reported)
I'll let you know if it happens again

**Comment by infiniteblock** [comment] 2022-05-14 04:24
same as #9 fixed in dev.

**Closed by infiniteblock** 2022-05-14 04:24 UTC
Labels: bug
