### ISSUE TITLE
Crash in rendering world

### ISSUE THREAD

**Issue by Gdanycz** [Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.12.2#67] opened 2023-04-23 17:48 UTC
**Describe the bug**
In rendering world game crash:

`The game crashed whilst exception ticking world entities
Error: java.lang.ClassCastException: matteroverdrive.tile.pipes.TileEntityHeavyMatterPipe cannot be cast to matteroverdrive.api.matter_network.IMatterNetworkConnection`

**please complete the following information:**
 - Forge Version: 1.12.2-forge-14.23.5.2860
 - Mods [mekanism, optifine, jei, ....]
 
 
[crash-2023-04-23_19.47.00-server.txt](https://github.com/Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.12.2/files/11304442/crash-2023-04-23_19.47.00-server.txt)

**Comment by infiniteblock** [comment] 2023-06-10 05:22
Fixed in Dev, Dupe of #69

**Closed by infiniteblock** 2023-06-10 05:22 UTC
Labels: bug
