### ISSUE TITLE
io.netty.handler.codec.EncoderException: String too big

### ISSUE THREAD

**Issue by Rsslone** [Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.12.2#64] opened 2023-02-24 07:34 UTC
**Describe the bug**
After dying to an android, the game kicks with the message
Internal Exception: io.netty.handler.codec.EncoderException: String too big (was 57409 bytes encoded, max 32767)
No feedback to the client. This is on a spongeforge env.

**To Reproduce**
Get killed by android
Observe being kicked

**Expected behavior**
After getting killed, to see a death respawn and continue on.

**Screenshots**

**please complete the following information:**
 - Forge Version:  forge-1.12.2-14.23.5.2860
 - Mods (321): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, /dank/null, A Lib, AE Additions, AE2 Unofficial Extended Life, AE2 Wireless Terminals (AE2WTLib), AI Improvements, AI Reducer, Advanced Rocketry, Aether Continuation, AgriCraft, AgriSeasons, Akashic Tome, Alchemistry, Alternating Flux, Animania, AppleCore, AppleSkin, Aquaculture, Athenaeum, Atum 2, AutoRegLib, Avaritia, B.A.S.E, Bad Wither No Cookie! Reloaded, Baubles, Better Records, BiblioCraft, Bigger Packets, please !, Biomes O' Plenty, Bird's nests, Blockcraftery, Bookshelf, Bountiful, Bountiful Baubles, Brandon's Core, Building Gadgets, CD4017BE_lib, Capability Adapter, Capsule, CasinoCraft, Ceramics, Chameleon, Chance Cubes, Chisel, Clumps, CodeChicken Lib, Collective, Comforts, Compact Machines 3, Construct's Armory, Cooking for Blockheads, Corail Tombstone, CosmeticArmorReworked, CraftStudio API, CraftTweaker JEI Support, CraftTweaker2, Crafting Tweaks, CreativeCore, CreativeCoreDummy, Culinary Construct, Cyberware, DarknessLib, Decocraft, Deep Mob Learning, Despawning Spawners, Doomlike Dungeons, Draconic Evolution, Dropt, DupeFix Project, Dynamic Surroundings, ElecCore, ElecCoreLoader, Elenai Dodge, Emerald & Obsidian Addons, Enchanting Plus, Enchantments Control, End: Reborn, Energy Control, Energy Meters, Engineer's Decor, Engineer's Doors, Expensive Death, Extra Alchemy, Extra Anvils, FTB Backups, FTB Library, FTB Money, FTB Money Currency Provider, FTB Quests, FTB Utilities, Fairy Lights, Fantastic Lib, Fast Leaf Decay, FastFurnace, FastWorkbench, Fire Spread Tweaks, Fish's Undead Rising, Fission Based Neutron Collector, FoamFix, FoamFixCore, Forge Endertech, Forge Microblocks, Forge Multipart CBE, Fossils and Archeology Revival, Frozen Fiend, Game Stages, Gamestage Books, Gauges and Switches, GottschCore, Grue, GuardsCraft, Guide-API, GunpowderLib, Had Enough Items, Hammer Core, Hardcore Darkness, Heroic Armory, Hooked, Hunger Overhaul, Iblis Headshots, Illagers+, Immersive Cables, Immersive Engineering, Immersive Petroleum, Immersive Technology, Improved Backpacks, InControl, Industrial Foregoing, Industrial Meat, Industrial Renewal, Industrial Wires, InfinityLib, InitialInventory, InstantUnify, Integration Foregoing, Iron Chest, Item Blacklist, Item Filters, Item Stages, ItemPhysic, IvToolkit, JAOPCA, JAOPCASingularities, JourneyMap, Just Enough Energistics, JustEnoughIDs, Kiwi, LLibrary, Large Ore Deposits, Level Up! Reloaded, LibrarianLib, LibrarianLib Stage 2, LibraryEx, Literal Ascension, LittleFrames, LittleTiles, LittleTilesCore, Lods of Emone, LoliASM, LootGames, Lost Aether Content, MTLib, Macaw's Bridges, Macaw's Doors, Macaw's Fences and Walls, Macaw's Paintings, Macaw's Paths & Pavings, Macaw's Roofs, Macaw's Trapdoors, Macaw's Windows, MalisisCore, MalisisDoors, Mantle, MatterOverdrive: Community Edition, McJtyLib, MekaTweaks, Mekanism, MineColonies, MineTweakerRecipeMaker, Minecraft Multipart Plugin, Minerva Library, MixinBooter, Mob Stages, Mod Tweaker, Modular ForceField System, More Avaritia, MoreTweaker, Morpheus, Mowzie's Mobs, MrTJPCore, Multi Mob Core, Multi-Storage, Mutant Beasts, Mystical Lib, Natura, Nature's Compass, NetherEx, NetherPortalFix, NoMoreRecipeConflict, NuclearCraft, Nutrition, OMLib, Open Modular Passive Defense, Open Modular Turrets, OpenBlocks, OpenComputers, OpenComputers (Core), OpenModsLib, OpenModsLib Core, OpenSecurity, OpticManager, Ore Stages, OreDictInit, OreLib Support Mod, Oxygen Core, Oxygen: Daily Rewards, Oxygen: Exchange, Oxygen: Friends List, Oxygen: Groups, Oxygen: Mail, Oxygen: Market, Oxygen: Merchants, Oxygen: Store, Oxygen: Teleportation, Pam's BrewCraft, Pam's HarvestCraft, Patchouli, Phosphor Lighting Engine, Pipe Master 2000, Placebo, PneumaticCraft: Repressurized, Portable Drill, Potion Core, Pouch Of Unknown, Primitive Mobs, Progressive Bosses, Project Intelligence, ProjectRed Core, ProjectRed Fabrication, ProjectRed Illumination, ProjectRed Integration, ProjectRed Transmission, Pyrotech, Quark, RTFM, Railcraft, RandomPatches, ReWIRED, Reach Fix, Realistic Armor Tiers, Reborn Core, RecipeStages, Recurrent Complex, Redstone Control, Redstone Flux, Respawnable Pets, Rough Mobs Revamped, Rustic, SG Craft, Scaling Health, Scannable, Serene Seasons, Shadowfacts' Forgelin, ShetiPhian-Core, Silent Lib, Simple Trophies, Spartan Shields, Spice of Life: Carrot Edition, SpongeForge, Steve's Carts 2, Storage Drawers, Structurize, Stupid Things, Super Sound Muffler: Revived, Surge, SwingThroughGrass, TOP Addons, TeaStory, Tesla Core Lib, Tesla Core Lib Registries, Thaumcraft, Thaumic Additions: Reconstructed, Thaumic Augmentation, The Aether, The Beneath, The One Probe, Thut Core, Thut's Elevators, ThutCore Compat, Tidy Chunk, Time Core, Tinkers' Construct, TogetherForever, Tool Belt, TorchMaster, Treasure2!, Tree Chopper, UniDict, Vaultopic, ViesCraft, Vulcanite, Vulpes library, WanionLib, Wireless Crafting Terminal 2, Wireless Fluid Terminal, Wireless Pattern Terminal, Wither Skeleton Tweaks, WrapUp, YUNG's Better Caves, YUNG's Better Mineshafts, ZenScroll, p455w0rd's Library, performant Mod, projectred-compat, spark
 - MO Version 1.12.2-0.8.2 & 1.12.2-0.8.1

**Additional context**
https://gist.github.com/Rsslone/8343f7b7b1b4ba9acbbcd86a1bdcc496

**Comment by Muffus16** [comment] 2023-02-24 19:28
duplicate of #61

**Comment by infiniteblock** [comment] 2023-04-29 22:34
Fixed In Dev.

**Closed by infiniteblock** 2023-04-29 22:34 UTC
Labels: bug
